---
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"

install:
    - pip install -r requirements.txt

script:
    - python setup.py flake8
    - python setup.py test

notifications:
    email: false
